# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e925381eb192a3ec7378133c5a659059e6641a65b55868c1399edbcd39452876b188b01eaeb7704332571ca2f90b57dd9bc45fe80653465bf6b282df47d0b3ca

test:
  secret_key_base: 0d2e1f3c801a4f54b5d754bf96625e14f44d2043bfc8f66cd73fae98a953e9f010695bd3a821d36dafd22ca7b07508e1c3bd26b59683891218d74ab48708162c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
